### ISSUE TITLE
Refactor Bytecode circuit to be a finite state machine

### ISSUE THREAD

**Issue by han0110** [privacy-scaling-explorations/zkevm-specs#151]
Currently Bytecode circuit is implemented with access to previous row, and with `is_final` indicator as main constraint flag, which seems not that straightforward to think about all kinds of possible branches.

This note proposes another way to implement it, by treating Bytecode circuit as a finite state machine just like EVM circuit, but with only 2 state: `Length` and  `Byte`. The pseudo code looks like:

```python3
Row = namedtuple(
    'Row',
    [
        'tag',
        'length', # renamed from hash_length
        'index',
        'value', # renamed from byte
        'is_code',
        'push_data_size', # renamed from byte_push_size
        'push_data_left',
        'hash',
        'value_rlc', # renamed from hash_rlc
    ],
)

curr, next = Row(), Row()

assert curr.tag in [Length, Byte]

# first row
if q_is_first:
    assert curr.tag == Length

# all except last row
if not q_is_last:

    if curr.tag == Length:
        assert curr.index == 0
        assert curr.value == curr.length

        if next.tag == Byte:
            assert next.length == curr.length
            assert next.index == 0
            assert next.is_code == 1
            assert next.hash == curr.hash
            assert next.value_rlc == 0
            # don't care next.value
            # don't care next.push_data_left

        if next.tag == Length:
            assert curr.length == 0
            assert curr.hash == EMPTY_HASH
            # don't care next.length
            # don't care next.index
            # don't care next.value
            # don't care next.is_code
            # don't care next.push_data_left
            # don't care next.hash
            # don't care next.value_rlc

    if curr.tag == Byte:
        assert push_data_size_table_lookup(curr.value, curr.push_data_size)
        assert curr.is_code == (curr.push_data_left == 0)
        if curr.is_code:
            assert next.push_data_left == curr.push_data_size
        else:
            assert next.push_data_left == curr.push_data_left - 1

        if next.tag == Byte:
            assert next.length == curr.length
            assert next.index == curr.index + 1
            assert next.hash == curr.hash
            assert next.value_rlc == curr.value_rlc * randomness + curr.value
            # don't care next.value

        if next.tag == Length:
            assert curr.index + 1 == curr.length
            assert keccak256_table_lookup(curr.hash, curr.length, curr.value_rlc)
            # don't care next.length
            # don't care next.index
            # don't care next.value
            # don't care next.hash
            # don't care next.value_rlc

# last row
if q_is_last:
    assert curr.tag == Length
    assert curr.length == 0
```

Finally the Bytecode circuit exports itself as `bytecode_table` with columns `(hash, tag, index, value, is_code)`.

Any feedback is appreciated.

**Comment by ed255** [comment]
Currently the bytecode circuit has the following columns (10 advice columns, 2 fixed):
- q_first
- q_last
- hash
- index
- byte
- is_code
- push_data_left
- hash_rlc
- hash_length
- byte_push_size
- is_final
- padding

And your proposal has (8 advice columns, 2 fixed):
- 'q_is_fixed'
- 'q_is_last'
- 'tag'
- 'length'
- 'index'
- 'value'
- 'is_code'
- 'push_data_left'
- 'hash'
- 'value_rlc'

If I understand it correctly in the refactor it would look like this:
| before | after | note |
| ---        | ---    | ---     |
| padding | tag | when tag is Padding |
| is_final | tag | `curr.Tag == Byte and next.Tag in [Length, Padding]` |
| hash | hash | |
| index | index | |
| byte | value | when tag is Byte |
| is_code | is_code | |
| push_data_left | byte_push_size | |
| hash_rlc | value_rlc | |
| hash_length | length | |
| byte_push_size | push_data_left | |

So your proposal uses 2 less advice columns, which is good!  And makes it explicit that it's a state machine, so it makes it easier to track all possible transitions to make sure we're not leaving any unattended state.

I'm in favor of this refactor mainly because state machines are easier to reason about and audit.

**Comment by han0110** [comment]
@ed255 Thanks for the comparing table! I made some naming change and I should add the reference directly in the pseudo code.

**Comment by han0110** [comment]
> Seems like it would be possible to do the padding by just filling up the block with zero length bytecodes by doing Length -> Length state transitions. The end condition is then that the last row needs to be a Length row with zero length.

@Brechtpd You are right! Let me update the pseudo code with this improvement.

> Isn't it necessary to do the `push_data_left_table_lookup` for each byte?

I missed byte range check actually, I think it still needs to be checked, let me bring `byte_push_size` back. Although like you said, keccak circuit might already do this, but I think it's fine to directly check here for now, we can remove it when we find it not necessary in the future.

**Comment by han0110** [comment]
Yes, the refactor doesn't change the `bytecode_table`, only trying to simplify the constraint of Bytecode circuit.

**Comment by leolara** [comment]
@ed255 @han0110 currently the code refers to a q_first collumn that we would need to assert that the first row should be a tag length.

Wouldn't it make the code more readable to have a tag == Padding instead of (Length, length=0)? Any performance drawbacks?

Perhaps a different name for the tag Length and the column length would also make the code more readable?

Perhaps the Length tag could be a Header tag, representing that the row is the header of the following bytecode?

**Comment by leolara** [comment]
@ed255 so I think that there is a typo and q_first has been written as q_is_fixed and that caused my confusion. I see we keep the q_first.

**Comment by leolara** [comment]
Why constrain index to be 0 in tag == Length cannot we just ignore that value?

**Comment by ed255** [comment]
> @ed255 @han0110 currently the code refers to a q_first collumn that we would need to assert that the first row should be a tag length.
> 
> Wouldn't it make the code more readable to have a tag == Padding instead of (Length, length=0)? Any performance drawbacks?

The design by Han reuses the state `tag == Length, length == 0` as padding.  This is interesting because we can add as many rows as needed like that without introducing any new value into the table, which means that we can use them as padding to get a fixed size table no matter how many bytes are really used.

The reason to avoid adding a new tag called `Padding` is that having only two tag values has benefits.  Having two tags `Length = 0, Byte = 1` allows creating the following selector degree 1 expressions:
- selector for Length tag: `1 - tag`
- selector for Byte tag: `tag`

If you have 3 tag values, the selectors are a bit more complex:
- selector for Length tag: `(tag - Byte)(tag - Pad)/n_1`
- selector for Byte tag: `(tag - Length)(tag - Pad)/n_2`
- selector for Pad tag: `(tag - Length)(tag - Byte)/n_3`

> Perhaps a different name for the tag Length and the column length would also make the code more readable?

What would you suggest?  Consider that this is the Bytecode table that needs to be exposed via the Bytecode circuit (the table needs to be embedded into the circuit): https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/tables.md#bytecode_table 

> Perhaps the Length tag could be a Header tag, representing that the row is the header of the following bytecode?

That makes sense, but then consider that we're also using this tag for a lookup following the table spec.  For the lookup we want to either verify a particular byte of the bytecode given its codeHash, or the length of the bytecode given its codeHash.

> @ed255 so I think that there is a typo and q_first has been written as q_is_fixed and that caused my confusion. I see we keep the q_first.

Ah I saw the typo in my message, I've fixed it :P

> Why constrain index to be 0 in tag == Length cannot we just ignore that value?

We need to guarantee that the Byte rows have index from 0 to length-1.  In the Byte->Byte transition we only verify that the index increases by 1, but we need to define a starting constraint.  That's why we must constrain index == 0 when tag == Length; otherwise the Byte rows could start at any index.

---

This document contains a diagram of the state machine that may help you https://hackmd.io/Cv5Pmh8fRyuuuwCFcCZdzg?both

**Comment by leolara** [comment]
@ed255 

If we didn't have a tag, we could have codehash == 0 for padding.

I am going to try to draft this out to see if I am not missing something on this idea.

**Comment by ed255** [comment]
> > We need to guarantee that the Byte rows have index from 0 to length-1. In the Byte->Byte transition we only verify that the index increases by 1, but we need to define a starting constraint. That's why we must constrain index == 0 when tag == Length; otherwise the Byte rows could start at any index.
> 
> **If in Length -> Byte transition we constrain that next.index == 0**, and then we constrain that the index increases in Byte -> Byte transitions, I don't see that we would need Lenght.index to be constrained to 0.

Ah you're right!  I missed that!  Indeed we force the index to start at `0` in the `Length -> Byte` transition, and not in the `Length` state.  So that constraint is technically unnecessary.

We still want to assign a known value to `index` when `tag == Length` thought, because we will do lookups and we need to know all the column values in a given row when `tag == Length`; and `0` is always a good known value to use when we don't care about the value.

> > That makes sense, but then consider that we're also using this tag for a lookup following the table spec. For the lookup we want to either verify a particular byte of the bytecode given its codeHash, or the length of the bytecode given its codeHash.
> 
> Now all Byte have also a length advise so perhaps it could be retrieved from any of those. The Length becomes more like a header then.

Yes, all Byte rows have a length column, but notice that this column is not exposed in the table.  If we want to expose it in the table, we'd need to add 1 more column to the table, which affects the lookup; and I think it's good to minimize the number of columns for a lookup table.  The reason to have a row with the Length is so that we can do a lookup to the length without growing the number of columns in the table.

> Perhaps this also mean that we don't need a Length tag, as we could match with (codehash, index ==0, length).

For that we would need to include the `length` column to the lookup table for the benefit of reducing 1 row for each bytecode.  I think it's desirable to avoid adding one more column to the lookup table; and the cost of having 1 extra row per bytecode is currently not a bottleneck.  But this is an option that would also work!

> If we didn't have a tag, we could have codehash == 0 for padding.
> 
> I am going to try to draft this out to see if I am not missing something on this idea.

I think it will work, and we'd need to extend the lookup table by 1 column (the `length` column).

**Comment by leolara** [comment]
@ed255 

> I think it will work, and we'd need to extend the lookup table by 1 column (the length column).

We also would get away with one less collumn (tag) and less rows. Which one is more worth it?

**Comment by leolara** [comment]
@ed255 bellow I put the code with one less column (tag) and less rows but one more lookup column (length).

```python
Row = namedtuple(
    'Row',
    [
        'length', # renamed from hash_length
        'index',
        'value', # renamed from byte
        'is_code',
        'push_data_size', # renamed from byte_push_size
        'push_data_left',
        'hash',
        'value_rlc', # renamed from hash_rlc
    ],
)

curr, next = Row(), Row()

# first row
if q_is_first:
    assert curr.index == 0
    assert curr.codehash != 0 # connot start with padding

# all except last row
if not q_is_last:

    if curr.codehash != 0:
        assert push_data_size_table_lookup(curr.value, curr.push_data_size)
        assert curr.is_code == (curr.push_data_left == 0)
        if curr.is_code:
            assert next.push_data_left == curr.push_data_size
        else:
            assert next.push_data_left == curr.push_data_left - 1

        if curr.index == 0:
            assert next.is_code == 1
            assert next.value_rlc == 0

        if next.index != 0: # bytecode continue
            # about next
            assert next.length == curr.length
            assert next.index == curr.index + 1
            assert next.hash == curr.hash
            assert next.value_rlc == curr.value_rlc * randomness + curr.value
            # don't care next.value

        if next.index == 0 or next.codehash == 0 : # bytecode ends
            assert curr.index + 1 == curr.length
            assert keccak256_table_lookup(curr.hash, curr.length, curr.value_rlc)

    if curr.codehash == 0:
        assert next.code_hash == 0 # only padding after padding

if q_is_last:
    assert curr.codehash == 0 # must be padding

```

**Comment by ed255** [comment]
> > I think it will work, and we'd need to extend the lookup table by 1 column (the length column).
> 
> We also would get away with one less collumn (tag) and less rows. Which one is more worth it?

Ah you're right on the fact that we'd remove the tag column, so we end up with the same number of columns in the lookup table.

After thinking about it I found a possible issue and two inconvenience:
- issue:
  - The lookup table also needs to contain the empty bytecode.  The empty bytecode has a code_hash but has no bytes.  How would you represent it?  If you represent it with the following row `[codeHash: EMPTY_HASH, length: 0, index: 0, isCode: 0, value: 0]`, then we would need to be very careful when querying bytes to the bytecode table, because querying the first byte of the `EMPTY_HASH` would succeed, but this is not desirable, because the `EMPTY_HASH` doesn't have any byte.
- inconvenience:
  - Any length query would need to know the first byte value of the bytecode.  If I want to lookup (codeHashA, lenA) I would need to do: `[codeHash: codeHashA, length: lenA, index: 0, isCode: 1, value: ???]`.  This requires allocating an extra cell to witness the value in order to do the lookup.
  - The same happens when querying a byte, we need to know the length.  If I want to lookup (codeHashA, indexB, isCodeB, valueB) I would do `[codeHash: codeHashA, length: ???, index: indexB, isCode: isCodeB, value: valueB]`.  I think in practice this may not be a problem because when we query a byte we also have the length in hand (to know the max queriable index)

**Comment by ed255** [comment]
Some quick comments on the code in https://github.com/privacy-scaling-explorations/zkevm-specs/issues/151#issuecomment-1343826866
- When you say `.codehash` is it the same as `.hash`?
- I see that you do two "different than zero" checks.  One for `hash` and one for `index`.  It's reasonable that you weren't aware of this, but the implementation of the constraint "different than zero" requires an extra witness, which would need be allocated in a new column probably. See this https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/ee1cfbdd15755371692a9bdb2e289fcf0c888860/gadgets/src/is_zero.rs#L53 and notice how you need a witness value of the inverse to prove that a number is either 0 or not.
- Having rows with `hash = 0` without any special tag can be dangerous, because we would need to make sure that they can't be queried by design from other circuits.

**Comment by leolara** [comment]
> The lookup table also needs to contain the empty bytecode. The empty bytecode has a code_hash but has no bytes. How would you represent it? If you represent it with the following row [codeHash: EMPTY_HASH, length: 0, index: 0, isCode: 0, value: 0], then we would need to be very careful when querying bytes to the bytecode table, because querying the first byte of the EMPTY_HASH would succeed, but this is not desirable, because the EMPTY_HASH doesn't have any byte.

I think I don't know enough to understand the problems this might cause. What is the value of `byte` when tag = `Length` does this matter?

> Any length query would need to know the first byte value of the bytecode. If I want to lookup (codeHashA, lenA) I would need to do: [codeHash: codeHashA, length: lenA, index: 0, isCode: 1, value: ???]. This requires allocating an extra cell to witness the value in order to do the lookup.

Ok

> The same happens when querying a byte, we need to know the length. If I want to lookup (codeHashA, indexB, isCodeB, valueB) I would do [codeHash: codeHashA, length: ???, index: indexB, isCode: isCodeB, value: valueB]. I think in practice this may not be a problem because when we query a byte we also have the length in hand (to know the max queriable index)

Is this not already happening in the original system from @han0110 ?

> When you say .codehash is it the same as .hash? 

Yes, fixed

> I see that you do two "different than zero" checks. One for hash and one for index. It's reasonable that you weren't aware of this...

Ok, I could fix this for example to use hash = EMPTY_HASH instead of 0. But for the index, yes it becomes more problematic.

> Having rows with hash = 0 without any special tag can be dangerous, because we would need to make sure that they can't be queried by design from other circuits.

I think I should use EMPTY_HASH instead of 0 in this case.

**Comment by leolara** [comment]
@ed255 

Another idea for optimisation: the value column currently can only be 0..255, what if we use other values to mean other things. For example 256 could mean that this is a Length row, and we wouldn't need the tag column.

**Comment by leolara** [comment]
@ed255 @han0110 

if the first value_rlc is 0

`assert next.value_rlc == 0`

and then each row includes the previous row value:

`assert next.value_rlc == curr.value_rlc * randomness + curr.value`

It seems we are not including the last byte valye into the value_rlc that we match with the keccak.

`assert keccak256_table_lookup(curr.hash, curr.length, curr.value_rlc)`.

Perhaps the first row should be itself's value, and then each row should be 

`assert next.value_rlc == curr.value_rlc * randomness + next.value`

**Comment by ed255** [comment]
> > The lookup table also needs to contain the empty bytecode. The empty bytecode has a code_hash but has no bytes. How would you represent it? If you represent it with the following row [codeHash: EMPTY_HASH, length: 0, index: 0, isCode: 0, value: 0], then we would need to be very careful when querying bytes to the bytecode table, because querying the first byte of the EMPTY_HASH would succeed, but this is not desirable, because the EMPTY_HASH doesn't have any byte.
> 
> I think I don't know enough to understand the problems this might cause. What is the value of `byte` when tag = `Length` does this matter?

In the proposal from Han there is no `byte` column.  There's a `value` column which is the length when tag = `Length` or a byte at an index when tag = `Byte`.

> > The same happens when querying a byte, we need to know the length. If I want to lookup (codeHashA, indexB, isCodeB, valueB) I would do [codeHash: codeHashA, length: ???, index: indexB, isCode: isCodeB, value: valueB]. I think in practice this may not be a problem because when we query a byte we also have the length in hand (to know the max queriable index)
> 
> Is this not already happening in the original system from @han0110 ?

This is not a problem in Han's proposal because there's no `length` column.  It follows this table layout https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/specs/tables.md#bytecode_table which allows querying length without knowing any byte value, and querying byte without knowing the length.

> So, after thinking about this, I think adding the tag Length row and tag collumn solves many problems.
> 
> Another thing that came up for me is that we are in the current implementation doing to checks for 0: for push_data_left and for length.
> 
> I have a couple of proposals:
> 
>     * push_data_left could go from n+1 to 1 instead of from n to 0, this way we compare to 1.

From a quick thought, I think both options work.

>     * length could be -1 (inv(1)) for the empty bytecodes.

The empty bytecode is a 0 length byte array, so it should have length = 0.  Why do you suggest setting it to -1?

> @ed255 @han0110
> 
> if the first value_rlc is 0
> 
> `assert next.value_rlc == 0`
> 
> and then each row includes the previous row value:
> 
> `assert next.value_rlc == curr.value_rlc * randomness + curr.value`
> 
> It seems we are not including the last byte valye into the value_rlc that we match with the keccak.
> 
> `assert keccak256_table_lookup(curr.hash, curr.length, curr.value_rlc)`.
> 
> Perhaps the first row should be itself's value, and then each row should be
> 
> `assert next.value_rlc == curr.value_rlc * randomness + next.value`

I think you're right with this analysis!  And I agree on your suggested solution.

**Comment by leolara** [comment]
Draft uploaded https://github.com/privacy-scaling-explorations/zkevm-specs/pull/340

**Comment by leolara** [comment]
PR ready for review: https://github.com/privacy-scaling-explorations/zkevm-specs/pull/340
