### ISSUE TITLE
Precompile: 0x04 identity

### ISSUE THREAD

**Issue by ChihChengLiang** [privacy-scaling-explorations/zkevm-specs#321]

**Comment by CPerezz** [comment]
I think we can leaverage a lot of work if we reuse the `CallDataCopy` or similar opcodes and try to adapt it or take major parts of it.
See: https://github.com/privacy-scaling-explorations/zkevm-specs/blob/master/src/zkevm_specs/evm/execution/calldatacopy.py and also CopyCircuit might help too: https://github.com/privacy-scaling-explorations/zkevm-circuits/blob/main/zkevm-circuits/src/copy_circuit.rs

**Comment by aguzmant103** [comment]
This includes creating a new namespace for identity pre-compile

**Comment by han0110** [comment]
Currently we store the information of return data only with a tuple `(LastCalleeId, LastCalleeReturnDataOffset, LastCalleeReturnDataLength)`, then read the memory from last callee directly only when `RETURNDATACOPY` is called. It works well because last callee already ends and the memory should be immutable.

However, this precompile replaces current return data with specified range memory of current call, where current call hasn't ended yet, so we couldn't just update the `LastCalleeId` to current call id, because the memory might still change.

So what we need to do in this precompile might be:

1. Treat current `rw_counter` as the imaginary call id
2. Use Copy circuit to copy from specified range memory of current call to this imaginary call.
3. Update current call's `(LastCalleeId, LastCalleeReturnDataOffset, LastCalleeReturnDataLength)`.

**Comment by CPerezz** [comment]
Makes complete sense! Thanks for sharing here @han0110 

I think with this @ashWhiteHat should be able to build up the specs and later implement this.

**Comment by aguzmant103** [comment]
Note: updating the architecture this week
